# Generated by Django 4.2.1 on 2024-03-11 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_add_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_product',
        ),
    ]
