# Generated by Django 4.2.1 on 2024-03-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_add_to_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=10)),
                ('user_name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('address_2', models.TextField()),
                ('country', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('pincode', models.IntegerField()),
                ('list', models.TextField()),
            ],
        ),
    ]
