# Generated by Django 4.2.1 on 2024-03-22 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_address_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
