# Generated by Django 4.2.1 on 2024-04-04 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_gallery',
            name='category_id',
        ),
    ]
