# Generated by Django 4.2.1 on 2024-04-04 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_category_gallery_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_product',
            name='product_id',
        ),
    ]
