# Generated by Django 4.2.1 on 2024-04-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_category_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_product',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
